NGINX_APP_NAME="nginx"

GALERA4_APP_NAME="galera-4"
MYSQL_WSREP_80_APP_NAME="mysql-wsrep-8.0"

APP_NAME=${APP_NAME-${NGINX_APP_NAME}}

LATEST_NGINX_VERSION="1.26.2"

LATEST_GALERA_4_VERSION="26.4.20"
LATEST_MYSQL_WSREP_80_VERSION="8.0.39"

declare -A MYSQL_WSREP_80_GALERA

MYSQL_WSREP_80_GALERA["${LATEST_MYSQL_WSREP_80_VERSION}"]="${LATEST_GALERA_4_VERSION}"
MYSQL_WSREP_80_GALERA["8.0.37"]="26.4.19"

APP_VERSION=${APP_VERSION:-${LATEST_NGINX_VERSION}}

refresh-yumcache() {
  echo "Refreshing yum cache..."

  yum clean all >/dev/null
  yum makecache >/dev/null
}
